[build]
  base = "app"
  command = "npm run build"
  publish = "build"

# SPA redirect rule - send all routes to index.html for React Router
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    # Security headers
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"
    
    # Cache static assets for 1 year
    Cache-Control = "public, max-age=31536000, immutable"

# Specific cache settings for the main HTML file
[[headers]]
  for = "/index.html"
  [headers.values]
    # Don't cache the main HTML file
    Cache-Control = "public, max-age=0, must-revalidate"

# Cache settings for static assets (JS, CSS, images)
[[headers]]
  for = "/static/*"
  [headers.values]
    # Cache static assets for 1 year with immutable flag
    Cache-Control = "public, max-age=31536000, immutable"

# Enable Cross-Origin Embedder Policy for SQLite WASM if needed
[[headers]]
  for = "/*"
  [headers.values]
    # These headers may be needed for SQLite WASM to work properly
    Cross-Origin-Embedder-Policy = "require-corp"
    Cross-Origin-Opener-Policy = "same-origin" 